# Generated by Django 5.2.4 on 2025-07-31 00:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0002_post_update_date_alter_post_create_date_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="post",
            name="modify_date",
        ),
    ]
