# Generated by Django 5.2.4 on 2025-07-31 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0003_remove_post_modify_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="uploaded_image",
            field=models.ImageField(blank=True, upload_to="images/"),
        ),
    ]
