# Generated by Django 5.2.4 on 2025-07-31 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0005_post_uploaded_file"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="downloaded_file",
            field=models.FileField(blank=True, upload_to="files/"),
        ),
    ]
